#!/usr/bin/env python3
"""Deterministic Docker generation and builds; no Docker needed for generate/check.

Repository-owned templates are trusted build code. CLI feature names select
registered fragments; they are never interpolated as Dockerfile instructions.
"""
from __future__ import annotations

import argparse
from contextlib import contextmanager
import fcntl
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parent.parent
MARKER = '# Generated by scripts/docker.py; temporary build context.'
BASE_PACKAGES = ('ca-certificates', 'gpg', 'gpgv', 'openssl', 'tini', 'tzdata', 'zstd')
HOOKS = {'BUILD_SETUP': 'build.Dockerfile', 'BUILD_CHECKS': 'build-check.Dockerfile',
         'RUNTIME_SETUP': 'runtime.Dockerfile', 'USER_CHECKS': 'check.Dockerfile'}


class DockerError(ValueError):
    """Invalid generation inputs or an unsafe output path."""


def relative(root: Path, name: str) -> Path:
    path = Path(name)
    if path.is_absolute() or not path.parts or any(p in ('.', '..') for p in path.parts):
        raise DockerError(f'expected a repository-relative path: {name}')
    result = root / path
    if any(p.is_symlink() for p in [result, *result.parents] if p != root.parent):
        raise DockerError(f'symlink is not allowed in build inputs/outputs: {name}')
    return result


def registry(root: Path) -> dict[str, dict]:
    result = {}
    for path in sorted((root / 'docker/experimental').glob('*/feature.json')):
        name = path.parent.name
        if not re.fullmatch(r'[a-z][a-z0-9-]*', name):
            raise DockerError(f'invalid feature name: {name}')
        data = json.loads(relative(root, str(path.relative_to(root))).read_text())
        allowed = {'description', 'build_packages', 'runtime_packages', 'requires', 'conflicts', 'volumes'}
        if not isinstance(data, dict) or set(data) != allowed or not isinstance(data['description'], str):
            raise DockerError(f'{name}: invalid feature manifest')
        for field in allowed - {'description'}:
            values = data[field]
            if not isinstance(values, list) or any(not isinstance(v, str) for v in values):
                raise DockerError(f'{name}: {field} must contain strings')
            if len(set(values)) != len(values):
                raise DockerError(f'{name}: duplicate {field}')
        for field in ('build_packages', 'runtime_packages'):
            if any(not re.fullmatch(r'[a-z0-9][a-z0-9+.-]*', v) for v in data[field]):
                raise DockerError(f'{name}: invalid package name')
        if any(not re.fullmatch(r'/[a-zA-Z0-9_/-]+', v) or '..' in v.split('/') for v in data['volumes']):
            raise DockerError(f'{name}: invalid volume path')
        result[name] = data
    for name, data in result.items():
        if any(v not in result or v == name for v in data['requires'] + data['conflicts']):
            raise DockerError(f'{name}: invalid feature dependency/conflict')
    return result


def selection(raw: str, features: dict[str, dict]) -> list[str]:
    names = [] if not raw.strip() else [v.strip() for v in raw.split(',')]
    if 'c-extension' in names and 'c-extension' not in features:
        raise DockerError('c-extension is reserved for the release-refactoring task and is not implemented')
    if any(name not in features for name in names) or len(set(names)) != len(names):
        raise DockerError('expected unique experimental features: ' + ', '.join(sorted(features)))
    selected = set(names)
    for name in names:
        if not set(features[name]['requires']) <= selected:
            raise DockerError(f'{name}: missing required experimental feature')
        if set(features[name]['conflicts']) & selected:
            raise DockerError(f'{name}: conflicting experimental features')
    # Dependencies precede their consumers; independent features are alphabetical.
    ordered = []
    while selected:
        ready = sorted(n for n in selected if set(features[n]['requires']) <= set(ordered))
        if not ready:
            raise DockerError('experimental feature dependency cycle')
        ordered.extend(ready)
        selected.difference_update(ready)
    return ordered


def render(root: Path, names: list[str], features: dict[str, dict]) -> str:
    text = relative(root, 'docker/repowatch.Dockerfile.in').read_text()
    values = {'FEATURES': ','.join(names) or 'none'}
    build_packages = sorted({p for n in names for p in features[n]['build_packages']})
    values['BUILD_PACKAGES'] = ("RUN apt-get update && apt-get install -y --no-install-recommends "
                                + ' '.join(build_packages) + " && rm -rf /var/lib/apt/lists/*") if build_packages else ''
    values['RUNTIME_PACKAGES'] = ' '.join(sorted(set(BASE_PACKAGES) | {
        p for n in names for p in features[n]['runtime_packages']}))
    values['VOLUMES'] = json.dumps(['/var/lib/repowatch'] + sorted({
        v for n in names for v in features[n]['volumes']} - {'/var/lib/repowatch'}))
    for slot, filename in HOOKS.items():
        fragments = [relative(root, f'docker/experimental/{name}/{filename}') for name in names]
        values[slot] = '\n'.join(p.read_text().rstrip() for p in fragments if p.exists())
    if set(re.findall(r'@@([A-Z_]+)@@', text)) != set(values):
        raise DockerError('template slots do not match the supported build hooks')
    for key, value in values.items():
        text = text.replace('@@' + key + '@@', value)
    if '@@' in text:
        raise DockerError('unresolved template slot')
    return text


def context_files(root: Path) -> list[str]:
    spec = json.loads(relative(root, 'docker/context.json').read_text())
    if not isinstance(spec, dict) or set(spec) != {'files', 'trees'}:
        raise DockerError('invalid context manifest')
    if (not isinstance(spec['files'], list) or any(not isinstance(p, str) for p in spec['files'])
            or not isinstance(spec['trees'], list)):
        raise DockerError('invalid context files/trees')
    files = set(spec['files'])
    for tree in spec['trees']:
        if (not isinstance(tree, dict) or set(tree) != {'path', 'suffixes'}
                or not isinstance(tree['path'], str) or not isinstance(tree['suffixes'], list)
                or not tree['suffixes'] or any(not isinstance(v, str) or not re.fullmatch(r'\.[a-z]+', v) for v in tree['suffixes'])):
            raise DockerError('invalid context tree')
        folder = relative(root, tree['path'])
        if not folder.is_dir():
            raise DockerError(f'missing source directory: {folder}')
        for parent, dirs, children in os.walk(folder, followlinks=False):
            dirs[:] = [d for d in dirs if not d.startswith('.') and d != '__pycache__']
            for name in dirs + children:
                path = Path(parent) / name
                if path.is_symlink():
                    raise DockerError(f'symlink in source tree: {path}')
            for name in children:
                path = Path(parent) / name
                if not name.startswith('.') and path.suffix in tree['suffixes']:
                    files.add(path.relative_to(root).as_posix())
    for name in files:
        if not re.fullmatch(r'[a-zA-Z0-9_./-]+', name) or not relative(root, name).is_file():
            raise DockerError(f'invalid or missing context file: {name}')
    return sorted(files)


def dockerignore(files: list[str]) -> str:
    # Enumerate exact files: an unrelated secret/database under src stays excluded.
    parents = {str(p) for name in files for p in Path(name).parents if str(p) != '.'}
    lines = [MARKER, '**']
    for parent in sorted(parents, key=lambda p: (p.count('/'), p)):
        # Open each ancestor for traversal, then keep its contents excluded.
        lines.extend(['!' + parent + '/', parent + '/*'])
    lines += ['!' + name for name in files]
    return '\n'.join(lines) + '\n'


def atomic(root: Path, name: str, text: str) -> None:
    path = relative(root, name)
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(mode='w', dir=path.parent, delete=False) as output:
        temporary = Path(output.name)
        try:
            output.write(text)
            output.flush()
            os.chmod(temporary, 0o644)
            os.replace(temporary, path)
        finally:
            temporary.unlink(missing_ok=True)


@contextmanager
def locked(root: Path):
    path = relative(root, 'build/docker.lock')
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        yield


def clean(root: Path) -> None:
    path = relative(root, '.dockerignore')
    if path.exists():
        if not path.read_text().startswith(MARKER + '\n'):
            raise DockerError('refusing to delete a .dockerignore not created by this generator')
        path.unlink()


def generate(root: Path, names: list[str], features: dict[str, dict]) -> str:
    base = render(root, [], features)
    variant = render(root, names, features)
    ignore = dockerignore(context_files(root))
    filename = 'Dockerfile' if not names else 'build/docker/' + '-'.join(names) + '/Dockerfile'
    # A Dockerfile-specific ignore file would silently override our context policy.
    if relative(root, filename + '.dockerignore').exists():
        raise DockerError('remove the conflicting Dockerfile-specific .dockerignore')
    nginx = relative(root, 'docker/nginx/Dockerfile.in').read_text()
    atomic(root, 'Dockerfile', base)
    atomic(root, 'docker/nginx/Dockerfile', nginx)
    if names:
        atomic(root, filename, variant)
    atomic(root, '.dockerignore', ignore)
    return filename


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=['generate', 'check', 'build', 'compose-build', 'clean', 'features'])
    parser.add_argument('--experimental', default=os.environ.get('DOCKER_EXPERIMENTAL', ''))
    args = parser.parse_args(argv)
    try:
        if args.command == 'clean':
            with locked(ROOT):
                clean(ROOT)
                clean(ROOT / 'docker/nginx')
            return 0
        features = registry(ROOT)
        names = selection(args.experimental, features)
        if args.command == 'features':
            for name, data in features.items():
                print(f'{name}: {data["description"]}')
            return 0
        if args.command == 'check':
            expected = render(ROOT, [], features)
            if relative(ROOT, 'Dockerfile').read_text() != expected:
                raise DockerError('Dockerfile is stale; run make docker-generate')
            if relative(ROOT, 'docker/nginx/Dockerfile').read_text() != relative(ROOT, 'docker/nginx/Dockerfile.in').read_text():
                raise DockerError('nginx Dockerfile is stale; run make docker-generate')
            render(ROOT, names, features)
            for name in features:
                required = {name}
                while True:
                    expanded = required | {r for n in required for r in features[n]['requires']}
                    if expanded == required:
                        break
                    required = expanded
                render(ROOT, selection(','.join(sorted(required)), features), features)
            dockerignore(context_files(ROOT))
            print('Docker templates and context rules are valid; .dockerignore is not required.')
            return 0
        engine = os.environ.get('DOCKER_ENGINE', 'docker')
        if args.command in ('build', 'compose-build') and shutil.which(engine) is None:
            raise DockerError(f'container build engine is not available: {engine}')
        with locked(ROOT):
            try:
                filename = generate(ROOT, names, features)
                if args.command == 'generate':
                    print(f'Generated {filename} and temporary .dockerignore')
                    return 0
                tag = os.environ.get('DOCKER_IMAGE') or ('repowatch:experimental-' + '-'.join(names) if names else 'repowatch:local')
                subprocess.run([engine, 'build', '--file', filename, '--tag', tag, '.'],
                               cwd=ROOT, check=True)
                if args.command == 'compose-build':
                    directory = ROOT / 'docker/nginx'
                    if (directory / 'Dockerfile.dockerignore').exists():
                        raise DockerError('remove the conflicting nginx Dockerfile-specific ignore file')
                    atomic(ROOT, 'docker/nginx/.dockerignore', dockerignore(['nginx.conf', 'policy.json', 'run.py']))
                    subprocess.run([engine, 'build', '--file', 'Dockerfile', '--build-arg',
                                    'REPOWATCH_IMAGE=' + tag, '--tag',
                                    os.environ.get('DOCKER_NGINX_IMAGE') or 'repowatch-nginx:trial', '.'],
                                   cwd=directory, check=True)
            finally:
                if args.command in ('build', 'compose-build'):
                    clean(ROOT)
                    if args.command == 'compose-build':
                        clean(ROOT / 'docker/nginx')
        return 0
    except (DockerError, OSError, json.JSONDecodeError, subprocess.CalledProcessError) as exc:
        print(f'docker: {exc}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
