"""Deterministic nginx renderer and transactional, root-owned publication.

Only structured YAML enters the renderer. Filesystem destinations are supplied
by the root-owned installation policy, never by the service-writable YAML.
"""
from __future__ import annotations

import fcntl
import hashlib
import ipaddress
import json
import logging
import os
from pathlib import Path
import re
import subprocess
import tempfile
from urllib.parse import urlsplit

from repowatch.config import Config, ConfigError, load_config
from repowatch.parsers.base import USER_AGENT
from repowatch.prefetch import _apt_top_segment, _apt_rpm_top_segment, _local_path, _repo_url_prefix
from repowatch.state import StateStore


def _path(value: str) -> str:
    if not isinstance(value, str) or not re.fullmatch(r'/[A-Za-z0-9_./+-]+', value) or '..' in value.split('/'):
        raise ConfigError('nginx: invalid filesystem path')
    return value


def _uri(value: str) -> str:
    if not re.fullmatch(r'/[A-Za-z0-9_./+~-]*', value) or any(x in value.split('/') for x in ('.', '..')):
        raise ConfigError('nginx: upstream/cache path contains unsupported characters')
    return value


def _compute_routes(config: Config) -> tuple[str, dict[str, tuple[str, str, str, int]], dict[str, str]]:
    """Shared route computation for render() and render_purge() — one source
    of truth for validation and for the (scheme, host, remote, ttl) per local
    prefix, so the purge key (built separately, see render_purge()) can never
    drift from the content locations it must exactly match."""
    settings = config.nginx
    routes: dict[str, tuple[str, str, str, int]] = {}
    kinds: dict[str, str] = {}
    for repo in config.repos:
        try:
            upstream = urlsplit(repo.upstream)
        except ValueError as exc:
            raise ConfigError(f"{repo.id}: invalid upstream URL") from exc
        if (upstream.scheme not in ('http', 'https') or not upstream.hostname
                or upstream.username or upstream.password or upstream.query or upstream.fragment
                or not re.fullmatch(r'[A-Za-z0-9.-]+(?::[0-9]{1,5})?', upstream.netloc)):
            raise ConfigError(f'{repo.id}: nginx requires a plain HTTP(S) upstream')
        try:
            upstream.port
        except ValueError as exc:
            raise ConfigError(f'{repo.id}: invalid upstream port') from exc
        remote = _uri(upstream.path.rstrip('/') + '/')
        if repo.type == 'apt-rpm':
            local = _uri(_apt_rpm_top_segment(repo).rstrip('/') + '/')
        elif repo.type == 'apt':
            local = _uri(_apt_top_segment(repo).rstrip('/') + '/')
        else:
            local = _uri(_repo_url_prefix(repo).rstrip('/') + '/')
            if repo.type == 'apk':
                # Parser appends the same suffix to upstream as prefetch does locally.
                suffix = f'{repo.arch}/'
                remote = _uri(remote + suffix)
        if local == '/':
            raise ConfigError(f'{repo.id}: root cache prefix is reserved')
        ttl = min(settings.index_ttl, config.effective_check_interval(repo))
        if ttl < 1:
            raise ConfigError('nginx: index TTL/check interval must be positive')
        route = (upstream.scheme, upstream.netloc, remote, ttl)
        if local in kinds and kinds[local] != repo.type:
            raise ConfigError(f"nginx: conflicting repository types for {local}")
        kinds[local] = repo.type
        previous = routes.get(local)
        if previous and previous[:3] != route[:3]:
            raise ConfigError(f'nginx: conflicting upstreams for {local}')
        if previous:
            route = (*route[:3], min(ttl, previous[3]))
        routes[local] = route
    prefixes = sorted(routes)
    if any(b.startswith(a) for i, a in enumerate(prefixes) for b in prefixes[i + 1:]):
        raise ConfigError('nginx: overlapping repository prefixes')
    key_prefix = settings.cache_key_version + ':' if settings.cache_key_version else ''
    return key_prefix, routes, kinds


def render(config: Config, *, cache_dir: str = '/var/cache/nginx/repowatch',
           access_log: str = '/var/log/nginx/repo-cache.access.log',
           purge_conf: str = '/etc/nginx/repowatch/purge.conf',
           dedup_conf: str = '/etc/nginx/repowatch/dedup.map') -> str:
    settings = config.nginx
    _path(cache_dir)
    _path(access_log)
    key_prefix, routes, kinds = _compute_routes(config)
    lines = [
        '# Generated by repowatch; edit YAML parameters, not this file.',
        f'proxy_cache_path {cache_dir} levels=1:2 keys_zone=repo_cache:64m max_size={settings.cache_max_size} inactive=180d use_temp_path=off;',
        "log_format cache_status '$remote_addr - $request \"$upstream_cache_status\" -> $upstream_addr';",
    ]
    if config.syslog_listener.enabled:
        # Distinguishes repowatch's OWN traffic (index checks + prefetch/
        # warm_cache — see parsers/base.py's USER_AGENT, already sent on
        # every such request) from real client requests, so the dashboard's
        # "Recent client requests" doesn't get polluted by our own
        # background activity — see syslog_listener.parse_syslog_line.
        # A map (not raw $http_user_agent in the log) for two reasons: (1)
        # real client user agents (e.g. "Debian APT-HTTP/1.3 (...)") contain
        # spaces, which would break the plain space-split log line format;
        # (2) it keeps a single, boring digit in the log instead of
        # attacker-influenceable free text. Both this map{} and the
        # repowatch_requests log_format live together here, only when
        # syslog_listener is enabled — the format is otherwise unused, and
        # referencing $repowatch_is_prefetch in it without the map{} that
        # actually declares the variable would be one more thing to keep in
        # sync for no reason.
        user_agent_prefix = re.escape(USER_AGENT.split('/', 1)[0])
        lines += [
            f'map $http_user_agent $repowatch_is_prefetch {{ default 0; "~*^{user_agent_prefix}/" 1; }}',
            "log_format repowatch_requests '$remote_addr $request_method $request_uri $status "
            "$upstream_cache_status $repowatch_is_prefetch';",
        ]
    if settings.enable_dedup:
        # map{} is http-context, not server-context (unlike purge's
        # location{}, see render_purge()) — it has to sit here, as a sibling
        # of proxy_cache_path/server{}, not inside the server block. The
        # actual (duplicate -> canonical) pairs live in the separate
        # dedup_conf file (render_dedup()), rewritten whenever
        # StateStore.find_duplicate_files() finds something new — this line
        # itself never changes once enable_dedup is on.
        # Keyed on $uri, NOT $request_uri: $request_uri is the ORIGINAL,
        # unmodified request URI and never changes across an internal
        # rewrite — keying on it here caused every internal redispatch to
        # re-evaluate to the same non-empty canonical URI forever, tripping
        # nginx's own "rewrite or internal redirection cycle" guard (found
        # by hand-testing against a real nginx before this shipped). $uri
        # DOES update after `rewrite`, so the second pass (now already at
        # the canonical path) maps to "" and the loop terminates in one hop.
        _path(dedup_conf)
        lines += [
            'map $uri $repowatch_canonical_uri {',
            f'    include {dedup_conf};',
            '}',
        ]
    lines += [
        'server {', f'    listen {settings.listen};', f'    server_name {settings.server_name};',
        f'    resolver {" ".join(settings.resolvers)} valid=300s ipv6=off;',
        '    resolver_timeout 5s;', f'    access_log {access_log} cache_status;',
        '    proxy_cache repo_cache;', f'    proxy_cache_valid 200 206 {settings.package_ttl}s;',
        '    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;',
        '    proxy_cache_lock on;', f'    proxy_cache_key "{key_prefix}$scheme$proxy_host$request_uri";',
        '    add_header X-Cache-Status $upstream_cache_status always;',
        '    location / { return 404; }',
    ]
    if config.syslog_listener.enabled:
        try:
            address = ipaddress.ip_address(config.syslog_listener.bind)
        except ValueError as exc:
            raise ConfigError('nginx: syslog bind must be a literal IP') from exc
        if not address.is_loopback or not 1 <= config.syslog_listener.port <= 65535:
            raise ConfigError('nginx: syslog destination must be loopback with a valid port')
        host = f'[{address}]' if address.version == 6 else str(address)
        lines.append(f'    access_log syslog:server={host}:{config.syslog_listener.port},facility=local6,tag=repowatch,severity=info repowatch_requests;')
    for number, (local, (scheme, host, remote, ttl)) in enumerate(sorted(routes.items())):
        # All mutable metadata (including signatures and apt translations) get short TTL.
        patterns = (r'[^/]+\.(db|files)(\.tar\.(gz|xz|zst))?(\.sig)?$',
                    r'dists/', r'APKINDEX\.tar\.gz$', r'repodata/', r'base/')
        kind = kinds[local]
        pattern = patterns[('pacman', 'apt', 'apk', 'dnf', 'apt-rpm').index(kind)]
        for index in (True, False):
            location = f'~ ^{re.escape(local)}{pattern}' if index else local
            lines += [f'    location {location} {{']
            if not index and settings.enable_dedup:
                # Dedup only ever applies to package files, never index
                # files — each repo's own index must always reflect ITS
                # OWN real state. $repowatch_canonical_uri is another
                # repo's local URI for the SAME (filename, content_hash);
                # `rewrite ... last` re-dispatches to THAT repo's own
                # location block, so whatever it does (TTL, upstream,
                # revalidate) applies unchanged. The cache key override
                # below (proxy_cache_key ...$uri, not the server-level
                # default's $request_uri) is what actually makes the
                # rewritten request land on the SAME cache entry the
                # canonical repo's own direct requests use — $request_uri is
                # the ORIGINAL, pre-rewrite URI and would keep the
                # duplicate's own path baked into the key even after
                # landing in the canonical location, silently defeating the
                # whole point (a real bug caught by hand-testing: it also
                # produced a second, separate cache entry instead of
                # sharing the canonical one).
                #
                # set $repowatch_canonical_uri ""; is NOT redundant — nginx
                # caches a map-derived variable's value for the rest of the
                # request once it's been read once, even across an internal
                # `rewrite ... last` redirect that changes $uri itself. Real
                # bug caught by hand-testing: without this reset, arriving
                # at the canonical repo's OWN location (which runs this
                # exact same check) re-read the STALE cached value from the
                # duplicate's location and rewrote again, forever — nginx's
                # "rewrite or internal redirection cycle" guard, not a
                # silent bug, but a 500 on every deduped request. The target
                # must be captured into a separate variable BEFORE the
                # reset, since `rewrite` evaluates its argument at the point
                # it runs, after this line.
                lines += [
                    '        if ($repowatch_canonical_uri) {',
                    '            set $repowatch_dedup_target $repowatch_canonical_uri;',
                    '            set $repowatch_canonical_uri "";',
                    '            rewrite ^ $repowatch_dedup_target last;',
                    '        }',
                ]
            lines.append(f'        set $rw_backend_{number} {host};')
            if local != remote:
                lines.append(f'        rewrite ^{re.escape(local)}(.*)$ {remote}$1 break;')
            lines += [f'        proxy_pass {scheme}://$rw_backend_{number};',
                      '        proxy_http_version 1.1;', f'        proxy_set_header Host {host};',
                      '        proxy_ssl_server_name on;']
            if index:
                if kind == 'pacman':
                    lines.append(f'        proxy_cache_key "{key_prefix}arch-index-v2:$scheme$proxy_host$request_uri";')
                lines.append(f'        proxy_cache_valid 200 206 {ttl}s;')
            else:
                if settings.enable_dedup:
                    # $uri (not $request_uri, see above) — applied to every
                    # content location uniformly when dedup is on, not just
                    # ones with a duplicate right now, so the key format
                    # never depends on whether a mapping currently exists.
                    # Harmless for everything else: package filenames never
                    # contain characters requiring percent-decoding or
                    # normalization here (see _uri()'s validation), so $uri
                    # and $request_uri are byte-identical for any request
                    # nginx would ever actually match against these
                    # locations — this doesn't invalidate the existing disk
                    # cache on upgrade.
                    lines.append(f'        proxy_cache_key "{key_prefix}$scheme$proxy_host$uri";')
                if kind == 'apt-rpm':
                    # ALT disttag/buildtime can change without changing the RPM
                    # basename. Revalidate these objects; the generic 180d immutable
                    # package TTL would keep an old rebuild under the same URL.
                    lines.append(f'        proxy_cache_valid 200 206 {min(ttl, settings.package_ttl)}s;')
                    lines.append('        proxy_cache_revalidate on;')
            lines.append('    }')
    if settings.enable_purge:
        # Purge/administrative locations live in their own included file
        # (render_purge()) instead of being interleaved into this per-repo
        # content-routing loop — keeps the main generated config readable as
        # the set of optional features grows, and keeps the purge file's own
        # diff/rollback independent of routing changes in apply().
        _path(purge_conf)
        lines.append(f'    include {purge_conf};')
    return '\n'.join(lines + ['}', ''])


def render_purge(config: Config) -> str:
    """Cache-eviction locations (docs_dev/ROADMAP.md item 24), generated
    separately from render() and pulled into the server block via a single
    `include` line there. Meant to be written to the path passed as
    render()'s purge_conf and included verbatim inside `server { ... }`, so
    it needs no server-level directives of its own.

    Returns just a header comment (no locations) when nginx.enable_purge is
    off, so callers can always call and write this unconditionally without
    checking the flag themselves — render() only ever includes the file when
    the flag is on, so an empty file here is inert either way.
    """
    key_prefix, routes, kinds = _compute_routes(config)
    lines = ['# Generated by repowatch; edit YAML parameters, not this file.']
    if config.nginx.enable_purge:
        for local, (scheme, host, remote, ttl) in sorted(routes.items()):
            # Reconstructs the SAME cache key a real package-file request
            # under `local` would produce (server-level
            # "{key_prefix}$scheme$proxy_host$request_uri" — package files
            # never hit the pacman arch-index-v2/apt-rpm revalidate branches
            # in render(), those are index-only). $scheme here is nginx's OWN
            # listening scheme (this generator never emits `listen ... ssl`,
            # so it's always literally "http" at runtime) — NOT the
            # upstream's scheme (`scheme` the Python variable, already
            # baked into `remote`/`proxy_pass` in render()) — a real bug
            # caught by hand-testing against a real nginx before wiring this
            # in: interpolating the upstream scheme into the key silently
            # purges the wrong (nonexistent) key. ${scheme} (braced) avoids
            # nginx parsing "$scheme<hostname>" as one variable name.
            # allow/deny (not limit_except): this location ONLY ever does
            # purge, no GET/HEAD content is served from it — restricting
            # the whole location to loopback is enough, no per-method logic
            # needed. External exposure would let anyone evict any cached
            # object; the same class of risk /metrics already guards
            # against for a different resource.
            lines += [
                f'    location ~ ^/purge{re.escape(local)}(.*)$ {{',
                '        allow 127.0.0.1;',
                '        deny all;',
                f'        proxy_cache_purge repo_cache "{key_prefix}${{scheme}}{host}{local}$1";',
                '    }',
            ]
    return '\n'.join(lines) + '\n'


def _map_literal(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def resolve_dedup_pairs(config: Config, rows: list[tuple[str, str, str]]) -> list[tuple[str, str]]:
    """Turns StateStore.find_duplicate_files() rows (repo ids + filename)
    into (duplicate_local_uri, canonical_local_uri) pairs, reusing
    prefetch._local_path — the same function that builds warm/purge URLs —
    so a dedup entry always points at exactly the URI that repo's own
    content location actually serves.

    A repo id that no longer exists in config.repos (removed since the hash
    was recorded — repo_packages rows are orphaned on repo removal, see
    CLAUDE.md) is silently skipped, same tolerance already applied to
    warmed_packages/prefetch_bans elsewhere.
    """
    by_id = {repo.id: repo for repo in config.repos}
    pairs: list[tuple[str, str]] = []
    for duplicate_id, canonical_id, filename in rows:
        duplicate_repo = by_id.get(duplicate_id)
        canonical_repo = by_id.get(canonical_id)
        if duplicate_repo is None or canonical_repo is None:
            continue
        pairs.append((_local_path(duplicate_repo, filename), _local_path(canonical_repo, filename)))
    return pairs


def render_dedup(config: Config, pairs: list[tuple[str, str]]) -> str:
    """Cross-repository dedup map (docs_dev/ROADMAP.md item 29), generated
    separately from render() and pulled in via the `map { include ...; }`
    block there (see render()) — unlike render_purge()'s location{} blocks,
    a bare list of "key" "value"; lines here IS valid nginx map-file syntax
    on its own, no wrapper needed.

    `pairs` are already-resolved local URIs (see resolve_dedup_pairs) —
    this function doesn't touch StateStore/config.repos lookups itself, to
    keep it a pure, easily-tested function of its arguments, same as
    render_purge().
    """
    lines = ['# Generated by repowatch; edit YAML parameters, not this file.']
    for duplicate_uri, canonical_uri in pairs:
        lines.append(f'{_map_literal(duplicate_uri)} {_map_literal(canonical_uri)};')
    return '\n'.join(lines) + '\n'


def _write(path: Path, data: str) -> None:
    fd, temporary = tempfile.mkstemp(prefix='.' + path.name, dir=path.parent)
    try:
        with os.fdopen(fd, 'w') as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def _check_policy_owner(policy_file: Path) -> None:
    for path in (policy_file, *policy_file.parents):
        info = path.lstat()
        if path.is_symlink() or info.st_uid != 0 or info.st_mode & 0o022:
            raise ConfigError('nginx policy and parent directories must be root-owned and not writable by others')

def _reload(nginx: str, nginx_conf: str, *, use_systemctl: bool) -> None:
    if use_systemctl:
        subprocess.run(['systemctl', 'reload', 'nginx.service'], check=True, capture_output=True, text=True, timeout=30)
    else:
        subprocess.run([nginx, '-s', 'reload', '-c', nginx_conf], check=True, capture_output=True, text=True, timeout=30)


def apply(config_path: str, policy_path: str, *, force: bool = False, use_systemctl: bool = True) -> bool:
    """Root timer/manual CLI share one transaction. No shell or writable code.

    active/previous/status/lock live in a root-owned directory outside the
    service's writable config/state directories. Site symlink is installed once
    by the operator. A failed candidate never replaces the last working backup.

    use_systemctl=False reloads nginx directly (`nginx -s reload`) instead of
    going through `systemctl reload nginx.service` — for the no-systemd
    standalone path (see supervisor.py); the systemd-managed CLI/timer path
    keeps the default.
    """
    policy_file = Path(policy_path)
    _check_policy_owner(policy_file)
    policy = json.loads(policy_file.read_text())
    directory = policy_file.parent
    active = directory / 'active.conf'
    previous = directory / 'previous.conf'
    purge_path = directory / 'purge.conf'
    previous_purge = directory / 'previous-purge.conf'
    dedup_path = directory / 'dedup.map'
    previous_dedup = directory / 'previous-dedup.map'
    status = directory / 'status.json'
    link = Path(policy['site_link'])
    if not link.is_symlink() or link.resolve() != active.resolve():
        raise ConfigError('nginx site symlink does not point to the managed active.conf')
    with (directory / 'apply.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        config = load_config(config_path)
        if not config.nginx.enabled:
            return False
        if config.nginx.cache_dir is not None and config.nginx.cache_dir != policy['cache_dir']:
            raise ConfigError(
                f"config.yaml declares nginx.cache_dir={config.nginx.cache_dir!r}, but the "
                f"installed policy actually uses cache_dir={policy['cache_dir']!r} — "
                f"these must match (see docs/configuration.md#nginx). Either update "
                f"nginx.cache_dir in config.yaml to the real path, or change the real one with "
                f"CACHE_DIR=... make install && sudo make activate."
            )
        candidate = render(config, cache_dir=policy['cache_dir'], access_log=policy['access_log'],
                            purge_conf=str(purge_path), dedup_conf=str(dedup_path))
        # render_purge()/render_dedup() are written unconditionally (empty/
        # comment-only when their flag is off) — render() only ever
        # `include`s them when the corresponding flag is on, so an idle file
        # on disk changes nothing; this avoids conditionally creating/
        # deleting a file across toggles.
        purge_candidate = render_purge(config)
        # find_duplicate_files() is a real query over repo_packages — only
        # run it when dedup is actually on, so leaving it off costs nothing
        # extra on every apply cycle (this timer runs every 15s).
        dedup_rows = StateStore(config.state_db).find_duplicate_files() if config.nginx.enable_dedup else []
        dedup_candidate = render_dedup(config, resolve_dedup_pairs(config, dedup_rows))
        digest = hashlib.sha256((candidate + purge_candidate + dedup_candidate).encode()).hexdigest()
        old = active.read_text() if active.exists() else None
        old_purge = purge_path.read_text() if purge_path.exists() else None
        old_dedup = dedup_path.read_text() if dedup_path.exists() else None
        if old == candidate and old_purge == purge_candidate and old_dedup == dedup_candidate and not force:
            return False
        nginx = policy['nginx_binary']
        command = [nginx, '-t', '-c', policy['nginx_conf']]
        _write(purge_path, purge_candidate)
        _write(dedup_path, dedup_candidate)
        _write(active, candidate)
        try:
            subprocess.run(command, check=True, capture_output=True, text=True, timeout=30)
            _reload(nginx, policy['nginx_conf'], use_systemctl=use_systemctl)
        except (OSError, subprocess.SubprocessError) as exc:
            logging.getLogger(__name__).error('nginx command failed: %s', getattr(exc, 'stderr', str(exc)))
            if old_purge is None:
                purge_path.unlink(missing_ok=True)
            else:
                _write(purge_path, old_purge)
            if old_dedup is None:
                dedup_path.unlink(missing_ok=True)
            else:
                _write(dedup_path, old_dedup)
            if old is None:
                active.unlink(missing_ok=True)
            else:
                _write(active, old)
                # Reload may have partially succeeded before its command failed.
                try:
                    subprocess.run(command, check=True, capture_output=True, timeout=30)
                    _reload(nginx, policy['nginx_conf'], use_systemctl=use_systemctl)
                except (OSError, subprocess.SubprocessError) as rollback:
                    _write(status, json.dumps({'ok': False, 'candidate': digest, 'rollback_failed': True}) + '\n')
                    raise ConfigError('nginx apply and rollback reload failed; inspect journal') from rollback
            _write(status, json.dumps({'ok': False, 'candidate': digest, 'rollback_failed': False}) + '\n')
            raise ConfigError('nginx apply failed; previous configuration restored') from exc
        if old is not None:
            _write(previous, old)
        if old_purge is not None:
            _write(previous_purge, old_purge)
        if old_dedup is not None:
            _write(previous_dedup, old_dedup)
        _write(status, json.dumps({'ok': True, 'active': digest}) + '\n')
        return True
