"""Deterministic nginx renderer and transactional, root-owned publication.

Only structured YAML enters the renderer. Filesystem destinations are supplied
by the root-owned installation policy, never by the service-writable YAML.
"""
from __future__ import annotations

import fcntl
import hashlib
import ipaddress
import json
import logging
import os
from pathlib import Path
import re
import subprocess
import tempfile
from urllib.parse import urlsplit

from repowatch.config import Config, ConfigError, RepoConfig, load_config
from repowatch.parsers.base import USER_AGENT
from repowatch.prefetch import _apt_top_segment, _apt_rpm_top_segment, _local_path, _repo_url_prefix
from repowatch.state import StateStore


def _path(value: str) -> str:
    if not isinstance(value, str) or not re.fullmatch(r'/[A-Za-z0-9_./+-]+', value) or '..' in value.split('/'):
        raise ConfigError('nginx: invalid filesystem path')
    return value


def _uri(value: str) -> str:
    if not re.fullmatch(r'/[A-Za-z0-9_./+~-]*', value) or any(x in value.split('/') for x in ('.', '..')):
        raise ConfigError('nginx: upstream/cache path contains unsupported characters')
    return value


def _compute_routes(config: Config) -> tuple[str, dict[str, tuple[str, str, str, int]], dict[str, str]]:
    """Shared route computation for render() and render_purge() — one source
    of truth for validation and for the (scheme, host, remote, ttl) per local
    prefix, so the purge key (built separately, see render_purge()) can never
    drift from the content locations it must exactly match."""
    settings = config.nginx
    routes: dict[str, tuple[str, str, str, int]] = {}
    kinds: dict[str, str] = {}
    for repo in config.repos:
        try:
            upstream = urlsplit(repo.upstream)
        except ValueError as exc:
            raise ConfigError(f"{repo.id}: invalid upstream URL") from exc
        if (upstream.scheme not in ('http', 'https') or not upstream.hostname
                or upstream.username or upstream.password or upstream.query or upstream.fragment
                or not re.fullmatch(r'[A-Za-z0-9.-]+(?::[0-9]{1,5})?', upstream.netloc)):
            raise ConfigError(f'{repo.id}: nginx requires a plain HTTP(S) upstream')
        try:
            upstream.port
        except ValueError as exc:
            raise ConfigError(f'{repo.id}: invalid upstream port') from exc
        remote = _uri(upstream.path.rstrip('/') + '/')
        if repo.type == 'apt-rpm':
            local = _uri(_apt_rpm_top_segment(repo).rstrip('/') + '/')
        elif repo.type == 'apt':
            local = _uri(_apt_top_segment(repo).rstrip('/') + '/')
        else:
            local = _uri(_repo_url_prefix(repo).rstrip('/') + '/')
            if repo.type == 'apk':
                # Parser appends the same suffix to upstream as prefetch does locally.
                suffix = f'{repo.arch}/'
                remote = _uri(remote + suffix)
        if local == '/':
            raise ConfigError(f'{repo.id}: root cache prefix is reserved')
        ttl = min(settings.index_ttl, config.effective_check_interval(repo))
        if ttl < 1:
            raise ConfigError('nginx: index TTL/check interval must be positive')
        route = (upstream.scheme, upstream.netloc, remote, ttl)
        if local in kinds and kinds[local] != repo.type:
            raise ConfigError(f"nginx: conflicting repository types for {local}")
        kinds[local] = repo.type
        previous = routes.get(local)
        if previous and previous[:3] != route[:3]:
            raise ConfigError(f'nginx: conflicting upstreams for {local}')
        if previous:
            route = (*route[:3], min(ttl, previous[3]))
        routes[local] = route
    prefixes = sorted(routes)
    if any(b.startswith(a) for i, a in enumerate(prefixes) for b in prefixes[i + 1:]):
        raise ConfigError('nginx: overlapping repository prefixes')
    key_prefix = settings.cache_key_version + ':' if settings.cache_key_version else ''
    return key_prefix, routes, kinds


def render(config: Config, *, cache_dir: str = '/var/cache/nginx/repowatch',
           access_log: str = '/var/log/nginx/repo-cache.access.log',
           purge_conf: str = '/etc/nginx/repowatch/purge.conf',
           dedup_conf: str = '/etc/nginx/repowatch/dedup.map',
           probe_conf: str = '/etc/nginx/repowatch/probe.conf',
           probe_js: str = '/etc/nginx/repowatch/probe.js') -> str:
    settings = config.nginx
    _path(cache_dir)
    _path(access_log)
    key_prefix, routes, kinds = _compute_routes(config)
    lines = [
        '# Generated by repowatch; edit YAML parameters, not this file.',
        f'proxy_cache_path {cache_dir} levels=1:2 keys_zone=repo_cache:64m max_size={settings.cache_max_size} inactive=180d use_temp_path=off;',
        "log_format cache_status '$remote_addr - $request \"$upstream_cache_status\" -> $upstream_addr';",
    ]
    if config.syslog_listener.enabled:
        # Distinguishes repowatch's OWN traffic (index checks + prefetch/
        # warm_cache — see parsers/base.py's USER_AGENT, already sent on
        # every such request) from real client requests, so the dashboard's
        # "Recent client requests" doesn't get polluted by our own
        # background activity — see syslog_listener.parse_syslog_line.
        # A map (not raw $http_user_agent in the log) for two reasons: (1)
        # real client user agents (e.g. "Debian APT-HTTP/1.3 (...)") contain
        # spaces, which would break the plain space-split log line format;
        # (2) it keeps a single, boring digit in the log instead of
        # attacker-influenceable free text. Both this map{} and the
        # repowatch_requests log_format live together here, only when
        # syslog_listener is enabled — the format is otherwise unused, and
        # referencing $repowatch_is_prefetch in it without the map{} that
        # actually declares the variable would be one more thing to keep in
        # sync for no reason.
        user_agent_prefix = re.escape(USER_AGENT.split('/', 1)[0])
        lines += [
            f'map $http_user_agent $repowatch_is_prefetch {{ default 0; "~*^{user_agent_prefix}/" 1; }}',
            "log_format repowatch_requests '$remote_addr $request_method $request_uri $status "
            "$upstream_cache_status $repowatch_is_prefetch';",
        ]
    if settings.enable_dedup:
        # map{} is http-context, not server-context (unlike purge's
        # location{}, see render_purge()) — it has to sit here, as a sibling
        # of proxy_cache_path/server{}, not inside the server block. The
        # actual (duplicate -> canonical) pairs live in the separate
        # dedup_conf file (render_dedup()), rewritten whenever
        # StateStore.find_duplicate_files() finds something new — this line
        # itself never changes once enable_dedup is on.
        # Keyed on $uri, NOT $request_uri: $request_uri is the ORIGINAL,
        # unmodified request URI and never changes across an internal
        # rewrite — keying on it here caused every internal redispatch to
        # re-evaluate to the same non-empty canonical URI forever, tripping
        # nginx's own "rewrite or internal redirection cycle" guard (found
        # by hand-testing against a real nginx before this shipped). $uri
        # DOES update after `rewrite`, so the second pass (now already at
        # the canonical path) maps to "" and the loop terminates in one hop.
        _path(dedup_conf)
        lines += [
            'map $uri $repowatch_canonical_uri {',
            f'    include {dedup_conf};',
            '}',
        ]
    if settings.enable_cache_probe:
        # http-context, like the dedup map{} above — js_import can't live
        # inside server{} (unlike purge/probe's own location{} blocks, see
        # render_probe_conf()). The imported module name ("cache_probe")
        # must match the export name render_probe_js() gives its handlers.
        _path(probe_js)
        lines.append(f'js_import cache_probe from {probe_js};')
    lines += [
        'server {', f'    listen {settings.listen};', f'    server_name {settings.server_name};',
        f'    resolver {" ".join(settings.resolvers)} valid=300s ipv6=off;',
        '    resolver_timeout 5s;', f'    access_log {access_log} cache_status;',
        '    proxy_cache repo_cache;', f'    proxy_cache_valid 200 206 {settings.package_ttl}s;',
        '    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;',
        '    proxy_cache_lock on;', f'    proxy_cache_key "{key_prefix}$scheme$proxy_host$request_uri";',
        '    add_header X-Cache-Status $upstream_cache_status always;',
        '    location / { return 404; }',
    ]
    if config.syslog_listener.enabled:
        try:
            address = ipaddress.ip_address(config.syslog_listener.bind)
        except ValueError as exc:
            raise ConfigError('nginx: syslog bind must be a literal IP') from exc
        if not address.is_loopback or not 1 <= config.syslog_listener.port <= 65535:
            raise ConfigError('nginx: syslog destination must be loopback with a valid port')
        host = f'[{address}]' if address.version == 6 else str(address)
        lines.append(f'    access_log syslog:server={host}:{config.syslog_listener.port},facility=local6,tag=repowatch,severity=info repowatch_requests;')
    for number, (local, (scheme, host, remote, ttl)) in enumerate(sorted(routes.items())):
        # All mutable metadata (including signatures and apt translations) get short TTL.
        patterns = (r'[^/]+\.(db|files)(\.tar\.(gz|xz|zst))?(\.sig)?$',
                    r'dists/', r'APKINDEX\.tar\.gz$', r'repodata/', r'base/', r'[^/]+-repodata$')
        kind = kinds[local]
        pattern = patterns[('pacman', 'apt', 'apk', 'dnf', 'apt-rpm', 'xbps').index(kind)]
        for index in (True, False):
            location = f'~ ^{re.escape(local)}{pattern}' if index else local
            lines += [f'    location {location} {{']
            if not index and settings.enable_dedup:
                # Dedup only ever applies to package files, never index
                # files — each repo's own index must always reflect ITS
                # OWN real state. $repowatch_canonical_uri is another
                # repo's local URI for the SAME (filename, content_hash);
                # `rewrite ... last` re-dispatches to THAT repo's own
                # location block, so whatever it does (TTL, upstream,
                # revalidate) applies unchanged. The cache key override
                # below (proxy_cache_key ...$uri, not the server-level
                # default's $request_uri) is what actually makes the
                # rewritten request land on the SAME cache entry the
                # canonical repo's own direct requests use — $request_uri is
                # the ORIGINAL, pre-rewrite URI and would keep the
                # duplicate's own path baked into the key even after
                # landing in the canonical location, silently defeating the
                # whole point (a real bug caught by hand-testing: it also
                # produced a second, separate cache entry instead of
                # sharing the canonical one).
                #
                # set $repowatch_canonical_uri ""; is NOT redundant — nginx
                # caches a map-derived variable's value for the rest of the
                # request once it's been read once, even across an internal
                # `rewrite ... last` redirect that changes $uri itself. Real
                # bug caught by hand-testing: without this reset, arriving
                # at the canonical repo's OWN location (which runs this
                # exact same check) re-read the STALE cached value from the
                # duplicate's location and rewrote again, forever — nginx's
                # "rewrite or internal redirection cycle" guard, not a
                # silent bug, but a 500 on every deduped request. The target
                # must be captured into a separate variable BEFORE the
                # reset, since `rewrite` evaluates its argument at the point
                # it runs, after this line.
                lines += [
                    '        if ($repowatch_canonical_uri) {',
                    '            set $repowatch_dedup_target $repowatch_canonical_uri;',
                    '            set $repowatch_canonical_uri "";',
                    '            rewrite ^ $repowatch_dedup_target last;',
                    '        }',
                ]
            lines.append(f'        set $rw_backend_{number} {host};')
            if local != remote:
                lines.append(f'        rewrite ^{re.escape(local)}(.*)$ {remote}$1 break;')
            lines += [f'        proxy_pass {scheme}://$rw_backend_{number};',
                      '        proxy_http_version 1.1;', f'        proxy_set_header Host {host};',
                      '        proxy_ssl_server_name on;']
            if index:
                if kind == 'pacman':
                    lines.append(f'        proxy_cache_key "{key_prefix}arch-index-v2:$scheme$proxy_host$request_uri";')
                lines.append(f'        proxy_cache_valid 200 206 {ttl}s;')
            else:
                if settings.enable_dedup:
                    # $uri (not $request_uri, see above) — applied to every
                    # content location uniformly when dedup is on, not just
                    # ones with a duplicate right now, so the key format
                    # never depends on whether a mapping currently exists.
                    # Harmless for everything else: package filenames never
                    # contain characters requiring percent-decoding or
                    # normalization here (see _uri()'s validation), so $uri
                    # and $request_uri are byte-identical for any request
                    # nginx would ever actually match against these
                    # locations — this doesn't invalidate the existing disk
                    # cache on upgrade.
                    lines.append(f'        proxy_cache_key "{key_prefix}$scheme$proxy_host$uri";')
                if kind == 'apt-rpm':
                    # ALT disttag/buildtime can change without changing the RPM
                    # basename. Revalidate these objects; the generic 180d immutable
                    # package TTL would keep an old rebuild under the same URL.
                    lines.append(f'        proxy_cache_valid 200 206 {min(ttl, settings.package_ttl)}s;')
                    lines.append('        proxy_cache_revalidate on;')
            lines.append('    }')
    if settings.enable_purge:
        # Purge/administrative locations live in their own included file
        # (render_purge()) instead of being interleaved into this per-repo
        # content-routing loop — keeps the main generated config readable as
        # the set of optional features grows, and keeps the purge file's own
        # diff/rollback independent of routing changes in apply().
        _path(purge_conf)
        lines.append(f'    include {purge_conf};')
    if settings.enable_cache_probe:
        # See render_probe_conf() — same "own included file, not interleaved
        # into per-repo routing" reasoning as purge_conf above.
        _path(probe_conf)
        lines.append(f'    include {probe_conf};')
    return '\n'.join(lines + ['}', ''])


def render_purge(config: Config) -> str:
    """Cache-eviction locations (docs_dev/ROADMAP.md item 24), generated
    separately from render() and pulled into the server block via a single
    `include` line there. Meant to be written to the path passed as
    render()'s purge_conf and included verbatim inside `server { ... }`, so
    it needs no server-level directives of its own.

    Returns just a header comment (no locations) when nginx.enable_purge is
    off, so callers can always call and write this unconditionally without
    checking the flag themselves — render() only ever includes the file when
    the flag is on, so an empty file here is inert either way.
    """
    settings = config.nginx
    key_prefix, routes, kinds = _compute_routes(config)
    lines = ['# Generated by repowatch; edit YAML parameters, not this file.']
    if settings.enable_purge:
        for local, (scheme, host, remote, ttl) in sorted(routes.items()):
            # Reconstructs the SAME cache key a real package-file request
            # under `local` would produce ($scheme here is nginx's OWN
            # listening scheme — this generator never emits `listen ... ssl`,
            # so it's always literally "http" at runtime — NOT the
            # upstream's scheme; ${scheme} braced avoids nginx parsing
            # "$scheme<hostname>" as one variable name; a real bug caught by
            # hand-testing before this ever shipped).
            #
            # The URI *basis* of that key depends on nginx.enable_dedup,
            # because render() itself uses two different bases there (see
            # its own "if settings.enable_dedup: proxy_cache_key
            # ...$uri" branch, applied to every package-file location
            # uniformly once dedup is on, not just repos with an actual
            # duplicate right now): dedup off -> the server-level default,
            # $request_uri (the ORIGINAL, pre-rewrite local request path,
            # i.e. `local` here); dedup on -> $uri, which after that same
            # location's own `rewrite ^{local}(.*)$ {remote}$1 break;` holds
            # the POST-rewrite upstream-relative path, i.e. `remote` here —
            # NOT `local`. Using `local` unconditionally (as this function
            # used to) is a REAL bug found on production (2026-09-12): with
            # dedup on, purge silently missed every real cache entry —
            # confirmed by hand, curl showed `X-Cache-Status: HIT` for a
            # file, then an immediate 404 from this same purge location for
            # the identical path, for every warmed package, on every repo,
            # not just ones with an actual duplicate.
            #
            # allow/deny (not limit_except): this location ONLY ever does
            # purge, no GET/HEAD content is served from it — restricting
            # the whole location to loopback is enough, no per-method logic
            # needed. External exposure would let anyone evict any cached
            # object; the same class of risk /metrics already guards
            # against for a different resource.
            basis = remote if settings.enable_dedup else local
            lines += [
                f'    location ~ ^/purge{re.escape(local)}(.*)$ {{',
                '        allow 127.0.0.1;',
                '        deny all;',
                f'        proxy_cache_purge repo_cache "{key_prefix}${{scheme}}{host}{basis}$1";',
                '    }',
            ]
        if settings.enable_cache_probe:
            # Route-independent purge (docs_dev/ROADMAP.md item 8) — accepts
            # an arbitrary already-known key verbatim, unlike the per-route
            # locations above. Needed for genuine orphans: a repo that was
            # removed from config.yaml (or had its dedup/url_template
            # settings changed) no longer has ANY route this generator can
            # rebuild a matching /purge<prefix> for, so the normal purge
            # mechanism above structurally cannot reach it. Discovery
            # (finding such a stale key at all) is cache_probe.py's
            # /cache-scan job — this location only ever deletes a key it's
            # explicitly handed, never searches for one itself. Gated on
            # BOTH flags: pointless without enable_purge (no module loaded
            # to do the actual eviction) and without enable_cache_probe
            # (nothing produces raw keys to feed it).
            lines += [
                '    location = /purge-raw {',
                '        allow 127.0.0.1;',
                '        deny all;',
                '        proxy_cache_purge repo_cache $arg_key;',
                '    }',
            ]
    return '\n'.join(lines) + '\n'


def compute_cache_key(config: Config, repo: RepoConfig, filename: str) -> str:
    """The exact literal proxy_cache_key string for one package file — the
    same value a real request through render()'s content location for this
    file would produce, computed here as a plain Python string instead of an
    nginx expression at request time.

    Used by cache_probe.py: to ask /cache-probe whether one SPECIFIC known
    package is really on disk (a non-destructive complement to
    prefetch.purge_selected(), which can only tell you by actually deleting
    the entry — see its own docstring on why a separate non-destructive
    check was rejected for a live HTTP GET/HEAD, a concern that doesn't
    apply here since this never touches upstream or proxy_cache at all, only
    stat()s a file); and to recognize which raw keys /cache-scan reads back
    from disk belong to a still-configured package, so anything left over is
    an orphan candidate for docs_dev/ROADMAP.md item 33.

    Reuses _compute_routes() — the same single source of truth render() and
    render_purge() already draw from — specifically to avoid reintroducing
    the dedup-basis mismatch bug documented on render_purge() above: this
    function and that one MUST compute identical keys for the same file.
    `local`'s scheme component is deliberately hardcoded to "http", not the
    route's (upstream) scheme — see the same point in render_purge()'s
    comment: it's nginx's own listening scheme at runtime, and this
    generator never emits `listen ... ssl`.

    Raises ValueError if `repo` isn't actually part of `config.repos`'
    current routing (e.g. a stale RepoConfig from before a reload) —
    callers always pass a repo drawn from the same `config` they pass here.
    """
    key_prefix, routes, _kinds = _compute_routes(config)
    local_path = _local_path(repo, filename)
    for local_prefix, (_scheme, host, remote_prefix, _ttl) in routes.items():
        if local_path.startswith(local_prefix):
            remote_path = remote_prefix + local_path[len(local_prefix):]
            basis = remote_path if config.nginx.enable_dedup else local_path
            return f'{key_prefix}http{host}{basis}'
    raise ValueError(f'{repo.id}: {filename!r} does not match any current nginx route')


def _js_string(value: str) -> str:
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'") + "'"


def render_probe_js(config: Config, *, cache_dir: str = '/var/cache/nginx/repowatch') -> str:
    """njs script body for the /cache-probe and /cache-scan locations
    (docs_dev/ROADMAP.md item 8, render_probe_conf()) — read-only cache
    introspection running inside the nginx worker itself (already `user
    www-data`-equivalent, unlike repowatch's own unprivileged process).

    Deliberately dumb: every byte of policy (which key, what counts as a
    match, what to do about an orphan) stays in Python, where it's covered
    by pytest — this only exposes two stateless filesystem primitives,
    mirroring the "njs computes nothing repowatch doesn't already know how
    to compute" principle agreed on for this feature. Both handlers were
    verified by hand against a real nginx 1.24 (Ubuntu, njs 0.8.2) cache
    directory before this was written — the cache file's on-disk header
    format is NOT public API, only empirically confirmed for that build:
    a fixed-size binary header followed by a literal "\\nKEY: <key>\\n" line
    immediately before the raw HTTP response. extractKey() searches for
    that marker instead of hardcoding the header's byte length, since the
    exact offset could differ with e.g. Vary — the marker text itself was
    what was actually confirmed stable across sample files, not one
    specific offset.

    Returns just a header comment when nginx.enable_cache_probe is off —
    render() never emits `js_import` for this file in that case, so nginx
    never parses it; the same "always safe to write unconditionally"
    contract as render_purge()/render_dedup().
    """
    settings = config.nginx
    lines = ['// Generated by repowatch; edit YAML parameters, not this file.']
    if not settings.enable_cache_probe:
        return '\n'.join(lines) + '\n'
    lines += [
        "const fs = require('fs');",
        f'const CACHE_DIR = {_js_string(cache_dir)};',
        "const KEY_MARKER = '\\nKEY: ';",
        '',
        'function cachePath(hash) {',
        "    return CACHE_DIR + '/' + hash.slice(-1) + '/' + hash.slice(-3, -1) + '/' + hash;",
        '}',
        '',
        'function probe(r) {',
        '    const key = r.args.key;',
        "    if (!key) { r.return(400, 'missing key\\n'); return; }",
        "    const hash = require('crypto').createHash('md5').update(key).digest('hex');",
        '    let result;',
        '    try {',
        '        const st = fs.statSync(cachePath(hash));',
        '        result = {exists: true, size: st.size, mtime: st.mtime};',
        '    } catch (e) {',
        '        result = {exists: false};',
        '    }',
        "    r.headersOut['Content-Type'] = 'application/json';",
        '    r.return(200, JSON.stringify(result));',
        '}',
        '',
        'function extractKey(buf) {',
        '    const idx = buf.indexOf(KEY_MARKER);',
        '    if (idx < 0) return null;',
        '    const start = idx + KEY_MARKER.length;',
        "    const nl = buf.indexOf('\\n', start);",
        '    if (nl < 0) return null;',
        '    return buf.slice(start, nl).toString();',
        '}',
        '',
        'function scan(r) {',
        '    const dir = r.args.dir;',
        # Validated against the fixed levels=1:2 shape (nginx.py's
        # proxy_cache_path) — also closes off path traversal via `dir`,
        # even though this location is loopback-only (defense in depth,
        # same posture as _uri()/_path() elsewhere in this module).
        "    if (!/^[0-9a-f]\\/[0-9a-f]{2}$/.test(dir || '')) { r.return(400, 'bad dir\\n'); return; }",
        "    const dirPath = CACHE_DIR + '/' + dir;",
        '    let entries = [];',
        '    try { entries = fs.readdirSync(dirPath); } catch (e) { entries = []; }',
        '    const results = entries.map((name) => {',
        '        try {',
        "            const full = dirPath + '/' + name;",
        '            const buf = fs.readFileSync(full);',
        '            const st = fs.statSync(full);',
        '            return {file: name, key: extractKey(buf), size: st.size, mtime: st.mtime};',
        '        } catch (e) {',
        '            return {file: name, error: String(e)};',
        '        }',
        '    });',
        "    r.headersOut['Content-Type'] = 'application/json';",
        '    r.return(200, JSON.stringify(results));',
        '}',
        '',
        'export default {probe, scan};',
    ]
    return '\n'.join(lines) + '\n'


def render_probe_conf(config: Config) -> str:
    """Locations for /cache-probe and /cache-scan (see render_probe_js()),
    generated separately from render() and pulled into the server block via
    a single `include` line there — same pattern as render_purge().

    Returns just a header comment when nginx.enable_cache_probe is off,
    same "always safe to call/write unconditionally" contract as
    render_purge()/render_dedup().
    """
    settings = config.nginx
    lines = ['# Generated by repowatch; edit YAML parameters, not this file.']
    if settings.enable_cache_probe:
        lines += [
            '    location = /cache-probe {',
            '        allow 127.0.0.1;',
            '        deny all;',
            '        js_content cache_probe.probe;',
            '    }',
            '    location = /cache-scan {',
            '        allow 127.0.0.1;',
            '        deny all;',
            '        js_content cache_probe.scan;',
            '    }',
        ]
    return '\n'.join(lines) + '\n'


def _map_literal(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def resolve_dedup_pairs(config: Config, rows: list[tuple[str, str, str]]) -> list[tuple[str, str]]:
    """Turns StateStore.find_duplicate_files() rows (repo ids + filename)
    into (duplicate_local_uri, canonical_local_uri) pairs, reusing
    prefetch._local_path — the same function that builds warm/purge URLs —
    so a dedup entry always points at exactly the URI that repo's own
    content location actually serves.

    A repo id that no longer exists in config.repos (removed since the hash
    was recorded — repo_packages rows are orphaned on repo removal, see
    CLAUDE.md) is silently skipped, same tolerance already applied to
    warmed_packages/prefetch_bans elsewhere.
    """
    by_id = {repo.id: repo for repo in config.repos}
    pairs: list[tuple[str, str]] = []
    for duplicate_id, canonical_id, filename in rows:
        duplicate_repo = by_id.get(duplicate_id)
        canonical_repo = by_id.get(canonical_id)
        if duplicate_repo is None or canonical_repo is None:
            continue
        pairs.append((_local_path(duplicate_repo, filename), _local_path(canonical_repo, filename)))
    return pairs


def render_dedup(config: Config, pairs: list[tuple[str, str]]) -> str:
    """Cross-repository dedup map (docs_dev/ROADMAP.md item 29), generated
    separately from render() and pulled in via the `map { include ...; }`
    block there (see render()) — unlike render_purge()'s location{} blocks,
    a bare list of "key" "value"; lines here IS valid nginx map-file syntax
    on its own, no wrapper needed.

    `pairs` are already-resolved local URIs (see resolve_dedup_pairs) —
    this function doesn't touch StateStore/config.repos lookups itself, to
    keep it a pure, easily-tested function of its arguments, same as
    render_purge().
    """
    lines = ['# Generated by repowatch; edit YAML parameters, not this file.']
    for duplicate_uri, canonical_uri in pairs:
        lines.append(f'{_map_literal(duplicate_uri)} {_map_literal(canonical_uri)};')
    return '\n'.join(lines) + '\n'


def _write(path: Path, data: str) -> None:
    fd, temporary = tempfile.mkstemp(prefix='.' + path.name, dir=path.parent)
    try:
        with os.fdopen(fd, 'w') as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def _check_policy_owner(policy_file: Path) -> None:
    for path in (policy_file, *policy_file.parents):
        info = path.lstat()
        if path.is_symlink() or info.st_uid != 0 or info.st_mode & 0o022:
            raise ConfigError('nginx policy and parent directories must be root-owned and not writable by others')

def _reload(nginx: str, nginx_conf: str, *, use_systemctl: bool) -> None:
    if use_systemctl:
        subprocess.run(['systemctl', 'reload', 'nginx.service'], check=True, capture_output=True, text=True, timeout=30)
    else:
        subprocess.run([nginx, '-s', 'reload', '-c', nginx_conf], check=True, capture_output=True, text=True, timeout=30)


def apply(config_path: str, policy_path: str, *, force: bool = False, use_systemctl: bool = True) -> bool:
    """Root timer/manual CLI share one transaction. No shell or writable code.

    active/previous/status/lock live in a root-owned directory outside the
    service's writable config/state directories. Site symlink is installed once
    by the operator. A failed candidate never replaces the last working backup.

    use_systemctl=False reloads nginx directly (`nginx -s reload`) instead of
    going through `systemctl reload nginx.service` — for the no-systemd
    standalone path (see supervisor.py); the systemd-managed CLI/timer path
    keeps the default.
    """
    policy_file = Path(policy_path)
    _check_policy_owner(policy_file)
    policy = json.loads(policy_file.read_text())
    directory = policy_file.parent
    active = directory / 'active.conf'
    previous = directory / 'previous.conf'
    purge_path = directory / 'purge.conf'
    previous_purge = directory / 'previous-purge.conf'
    dedup_path = directory / 'dedup.map'
    previous_dedup = directory / 'previous-dedup.map'
    probe_conf_path = directory / 'probe.conf'
    previous_probe_conf = directory / 'previous-probe.conf'
    probe_js_path = directory / 'probe.js'
    previous_probe_js = directory / 'previous-probe.js'
    status = directory / 'status.json'
    link = Path(policy['site_link'])
    if not link.is_symlink() or link.resolve() != active.resolve():
        raise ConfigError('nginx site symlink does not point to the managed active.conf')
    with (directory / 'apply.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        config = load_config(config_path)
        if not config.nginx.enabled:
            return False
        if config.nginx.cache_dir is not None and config.nginx.cache_dir != policy['cache_dir']:
            raise ConfigError(
                f"config.yaml declares nginx.cache_dir={config.nginx.cache_dir!r}, but the "
                f"installed policy actually uses cache_dir={policy['cache_dir']!r} — "
                f"these must match (see docs/configuration.md#nginx). Either update "
                f"nginx.cache_dir in config.yaml to the real path, or change the real one with "
                f"CACHE_DIR=... make install && sudo make activate."
            )
        candidate = render(config, cache_dir=policy['cache_dir'], access_log=policy['access_log'],
                            purge_conf=str(purge_path), dedup_conf=str(dedup_path),
                            probe_conf=str(probe_conf_path), probe_js=str(probe_js_path))
        # render_purge()/render_dedup()/render_probe_conf()/render_probe_js()
        # are written unconditionally (empty/comment-only when their flag is
        # off) — render() only ever `include`s/`js_import`s them when the
        # corresponding flag is on, so an idle file on disk changes nothing;
        # this avoids conditionally creating/deleting a file across toggles.
        purge_candidate = render_purge(config)
        # find_duplicate_files() is a real query over repo_packages — only
        # run it when dedup is actually on, so leaving it off costs nothing
        # extra on every apply cycle (this timer runs every 15s).
        dedup_rows = StateStore(config.state_db).find_duplicate_files() if config.nginx.enable_dedup else []
        dedup_candidate = render_dedup(config, resolve_dedup_pairs(config, dedup_rows))
        probe_conf_candidate = render_probe_conf(config)
        probe_js_candidate = render_probe_js(config, cache_dir=policy['cache_dir'])
        digest = hashlib.sha256((
            candidate + purge_candidate + dedup_candidate + probe_conf_candidate + probe_js_candidate
        ).encode()).hexdigest()
        old = active.read_text() if active.exists() else None
        old_purge = purge_path.read_text() if purge_path.exists() else None
        old_dedup = dedup_path.read_text() if dedup_path.exists() else None
        old_probe_conf = probe_conf_path.read_text() if probe_conf_path.exists() else None
        old_probe_js = probe_js_path.read_text() if probe_js_path.exists() else None
        if (old == candidate and old_purge == purge_candidate and old_dedup == dedup_candidate
                and old_probe_conf == probe_conf_candidate and old_probe_js == probe_js_candidate
                and not force):
            return False
        nginx = policy['nginx_binary']
        command = [nginx, '-t', '-c', policy['nginx_conf']]
        _write(purge_path, purge_candidate)
        _write(dedup_path, dedup_candidate)
        _write(probe_conf_path, probe_conf_candidate)
        _write(probe_js_path, probe_js_candidate)
        _write(active, candidate)
        try:
            subprocess.run(command, check=True, capture_output=True, text=True, timeout=30)
            _reload(nginx, policy['nginx_conf'], use_systemctl=use_systemctl)
        except (OSError, subprocess.SubprocessError) as exc:
            logging.getLogger(__name__).error('nginx command failed: %s', getattr(exc, 'stderr', str(exc)))
            if old_purge is None:
                purge_path.unlink(missing_ok=True)
            else:
                _write(purge_path, old_purge)
            if old_dedup is None:
                dedup_path.unlink(missing_ok=True)
            else:
                _write(dedup_path, old_dedup)
            if old_probe_conf is None:
                probe_conf_path.unlink(missing_ok=True)
            else:
                _write(probe_conf_path, old_probe_conf)
            if old_probe_js is None:
                probe_js_path.unlink(missing_ok=True)
            else:
                _write(probe_js_path, old_probe_js)
            if old is None:
                active.unlink(missing_ok=True)
            else:
                _write(active, old)
                # Reload may have partially succeeded before its command failed.
                try:
                    subprocess.run(command, check=True, capture_output=True, timeout=30)
                    _reload(nginx, policy['nginx_conf'], use_systemctl=use_systemctl)
                except (OSError, subprocess.SubprocessError) as rollback:
                    _write(status, json.dumps({'ok': False, 'candidate': digest, 'rollback_failed': True}) + '\n')
                    raise ConfigError('nginx apply and rollback reload failed; inspect journal') from rollback
            _write(status, json.dumps({'ok': False, 'candidate': digest, 'rollback_failed': False}) + '\n')
            raise ConfigError('nginx apply failed; previous configuration restored') from exc
        if old is not None:
            _write(previous, old)
        if old_purge is not None:
            _write(previous_purge, old_purge)
        if old_dedup is not None:
            _write(previous_dedup, old_dedup)
        if old_probe_conf is not None:
            _write(previous_probe_conf, old_probe_conf)
        if old_probe_js is not None:
            _write(previous_probe_js, old_probe_js)
        _write(status, json.dumps({'ok': True, 'active': digest}) + '\n')
        return True
