"""Deterministic nginx renderer and transactional, root-owned publication.

Only structured YAML enters the renderer. Filesystem destinations are supplied
by the root-owned installation policy, never by the service-writable YAML.
"""
from __future__ import annotations

import fcntl
import hashlib
import ipaddress
import json
import logging
import os
from pathlib import Path
import re
import subprocess
import tempfile
from urllib.parse import urlsplit

from repowatch.config import Config, ConfigError, load_config
from repowatch.prefetch import _apt_top_segment, _apt_rpm_top_segment, _repo_url_prefix


def _path(value: str) -> str:
    if not isinstance(value, str) or not re.fullmatch(r'/[A-Za-z0-9_./+-]+', value) or '..' in value.split('/'):
        raise ConfigError('nginx: invalid filesystem path')
    return value


def _uri(value: str) -> str:
    if not re.fullmatch(r'/[A-Za-z0-9_./+~-]*', value) or any(x in value.split('/') for x in ('.', '..')):
        raise ConfigError('nginx: upstream/cache path contains unsupported characters')
    return value


def render(config: Config, *, cache_dir: str = '/var/cache/nginx/repowatch',
           access_log: str = '/var/log/nginx/repo-cache.access.log') -> str:
    settings = config.nginx
    _path(cache_dir)
    _path(access_log)
    routes: dict[str, tuple[str, str, str, int]] = {}
    kinds: dict[str, str] = {}
    for repo in config.repos:
        try:
            upstream = urlsplit(repo.upstream)
        except ValueError as exc:
            raise ConfigError(f"{repo.id}: invalid upstream URL") from exc
        if (upstream.scheme not in ('http', 'https') or not upstream.hostname
                or upstream.username or upstream.password or upstream.query or upstream.fragment
                or not re.fullmatch(r'[A-Za-z0-9.-]+(?::[0-9]{1,5})?', upstream.netloc)):
            raise ConfigError(f'{repo.id}: nginx requires a plain HTTP(S) upstream')
        try:
            upstream.port
        except ValueError as exc:
            raise ConfigError(f'{repo.id}: invalid upstream port') from exc
        remote = _uri(upstream.path.rstrip('/') + '/')
        if repo.type == 'apt-rpm':
            local = _uri(_apt_rpm_top_segment(repo).rstrip('/') + '/')
        elif repo.type == 'apt':
            local = _uri(_apt_top_segment(repo).rstrip('/') + '/')
        else:
            local = _uri(_repo_url_prefix(repo).rstrip('/') + '/')
            if repo.type == 'apk':
                # Parser appends the same suffix to upstream as prefetch does locally.
                suffix = f'{repo.arch}/'
                remote = _uri(remote + suffix)
        if local == '/':
            raise ConfigError(f'{repo.id}: root cache prefix is reserved')
        ttl = min(settings.index_ttl, config.effective_check_interval(repo))
        if ttl < 1:
            raise ConfigError('nginx: index TTL/check interval must be positive')
        route = (upstream.scheme, upstream.netloc, remote, ttl)
        if local in kinds and kinds[local] != repo.type:
            raise ConfigError(f"nginx: conflicting repository types for {local}")
        kinds[local] = repo.type
        previous = routes.get(local)
        if previous and previous[:3] != route[:3]:
            raise ConfigError(f'nginx: conflicting upstreams for {local}')
        if previous:
            route = (*route[:3], min(ttl, previous[3]))
        routes[local] = route
    prefixes = sorted(routes)
    if any(b.startswith(a) for i, a in enumerate(prefixes) for b in prefixes[i + 1:]):
        raise ConfigError('nginx: overlapping repository prefixes')
    key_prefix = settings.cache_key_version + ':' if settings.cache_key_version else ''
    lines = [
        '# Generated by repowatch; edit YAML parameters, not this file.',
        f'proxy_cache_path {cache_dir} levels=1:2 keys_zone=repo_cache:64m max_size={settings.cache_max_size} inactive=180d use_temp_path=off;',
        "log_format cache_status '$remote_addr - $request \"$upstream_cache_status\" -> $upstream_addr';",
        "log_format repowatch_requests '$remote_addr $request_method $request_uri $status $upstream_cache_status';",
        'server {', f'    listen {settings.listen};', f'    server_name {settings.server_name};',
        f'    resolver {" ".join(settings.resolvers)} valid=300s ipv6=off;',
        '    resolver_timeout 5s;', f'    access_log {access_log} cache_status;',
        '    proxy_cache repo_cache;', f'    proxy_cache_valid 200 206 {settings.package_ttl}s;',
        '    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;',
        '    proxy_cache_lock on;', f'    proxy_cache_key "{key_prefix}$scheme$proxy_host$request_uri";',
        '    add_header X-Cache-Status $upstream_cache_status always;',
        '    location / { return 404; }',
    ]
    if config.syslog_listener.enabled:
        try:
            address = ipaddress.ip_address(config.syslog_listener.bind)
        except ValueError as exc:
            raise ConfigError('nginx: syslog bind must be a literal IP') from exc
        if not address.is_loopback or not 1 <= config.syslog_listener.port <= 65535:
            raise ConfigError('nginx: syslog destination must be loopback with a valid port')
        host = f'[{address}]' if address.version == 6 else str(address)
        lines.append(f'    access_log syslog:server={host}:{config.syslog_listener.port},facility=local6,tag=repowatch,severity=info repowatch_requests;')
    for number, (local, (scheme, host, remote, ttl)) in enumerate(sorted(routes.items())):
        # All mutable metadata (including signatures and apt translations) get short TTL.
        patterns = (r'[^/]+\.(db|files)(\.tar\.(gz|xz|zst))?(\.sig)?$',
                    r'dists/', r'APKINDEX\.tar\.gz$', r'repodata/', r'base/')
        kind = kinds[local]
        pattern = patterns[('pacman', 'apt', 'apk', 'dnf', 'apt-rpm').index(kind)]
        for index in (True, False):
            location = f'~ ^{re.escape(local)}{pattern}' if index else local
            lines += [f'    location {location} {{', f'        set $rw_backend_{number} {host};']
            if local != remote:
                lines.append(f'        rewrite ^{re.escape(local)}(.*)$ {remote}$1 break;')
            lines += [f'        proxy_pass {scheme}://$rw_backend_{number};',
                      '        proxy_http_version 1.1;', f'        proxy_set_header Host {host};',
                      '        proxy_ssl_server_name on;']
            if index:
                if kind == 'pacman':
                    lines.append(f'        proxy_cache_key "{key_prefix}arch-index-v2:$scheme$proxy_host$request_uri";')
                lines.append(f'        proxy_cache_valid 200 206 {ttl}s;')
            elif kind == 'apt-rpm':
                # ALT disttag/buildtime can change without changing the RPM
                # basename. Revalidate these objects; the generic 180d immutable
                # package TTL would keep an old rebuild under the same URL.
                lines.append(f'        proxy_cache_valid 200 206 {min(ttl, settings.package_ttl)}s;')
                lines.append('        proxy_cache_revalidate on;')
            lines.append('    }')
    return '\n'.join(lines + ['}', ''])


def _write(path: Path, data: str) -> None:
    fd, temporary = tempfile.mkstemp(prefix='.' + path.name, dir=path.parent)
    try:
        with os.fdopen(fd, 'w') as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def _check_policy_owner(policy_file: Path) -> None:
    for path in (policy_file, *policy_file.parents):
        info = path.lstat()
        if path.is_symlink() or info.st_uid != 0 or info.st_mode & 0o022:
            raise ConfigError('nginx policy and parent directories must be root-owned and not writable by others')

def _reload(nginx: str, nginx_conf: str, *, use_systemctl: bool) -> None:
    if use_systemctl:
        subprocess.run(['systemctl', 'reload', 'nginx.service'], check=True, capture_output=True, text=True, timeout=30)
    else:
        subprocess.run([nginx, '-s', 'reload', '-c', nginx_conf], check=True, capture_output=True, text=True, timeout=30)


def apply(config_path: str, policy_path: str, *, force: bool = False, use_systemctl: bool = True) -> bool:
    """Root timer/manual CLI share one transaction. No shell or writable code.

    active/previous/status/lock live in a root-owned directory outside the
    service's writable config/state directories. Site symlink is installed once
    by the operator. A failed candidate never replaces the last working backup.

    use_systemctl=False reloads nginx directly (`nginx -s reload`) instead of
    going through `systemctl reload nginx.service` — for the no-systemd
    standalone path (see supervisor.py); the systemd-managed CLI/timer path
    keeps the default.
    """
    policy_file = Path(policy_path)
    _check_policy_owner(policy_file)
    policy = json.loads(policy_file.read_text())
    directory = policy_file.parent
    active = directory / 'active.conf'
    previous = directory / 'previous.conf'
    status = directory / 'status.json'
    link = Path(policy['site_link'])
    if not link.is_symlink() or link.resolve() != active.resolve():
        raise ConfigError('nginx site symlink does not point to the managed active.conf')
    with (directory / 'apply.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        config = load_config(config_path)
        if not config.nginx.enabled:
            return False
        if config.nginx.cache_dir is not None and config.nginx.cache_dir != policy['cache_dir']:
            raise ConfigError(
                f"config.yaml declares nginx.cache_dir={config.nginx.cache_dir!r}, but the "
                f"installed policy actually uses cache_dir={policy['cache_dir']!r} — "
                f"these must match (see docs/configuration.md#nginx). Either update "
                f"nginx.cache_dir in config.yaml to the real path, or change the real one with "
                f"CACHE_DIR=... make install && sudo make activate."
            )
        candidate = render(config, cache_dir=policy['cache_dir'], access_log=policy['access_log'])
        digest = hashlib.sha256(candidate.encode()).hexdigest()
        old = active.read_text() if active.exists() else None
        if old == candidate and not force:
            return False
        nginx = policy['nginx_binary']
        command = [nginx, '-t', '-c', policy['nginx_conf']]
        _write(active, candidate)
        try:
            subprocess.run(command, check=True, capture_output=True, text=True, timeout=30)
            _reload(nginx, policy['nginx_conf'], use_systemctl=use_systemctl)
        except (OSError, subprocess.SubprocessError) as exc:
            logging.getLogger(__name__).error('nginx command failed: %s', getattr(exc, 'stderr', str(exc)))
            if old is None:
                active.unlink(missing_ok=True)
            else:
                _write(active, old)
                # Reload may have partially succeeded before its command failed.
                try:
                    subprocess.run(command, check=True, capture_output=True, timeout=30)
                    _reload(nginx, policy['nginx_conf'], use_systemctl=use_systemctl)
                except (OSError, subprocess.SubprocessError) as rollback:
                    _write(status, json.dumps({'ok': False, 'candidate': digest, 'rollback_failed': True}) + '\n')
                    raise ConfigError('nginx apply and rollback reload failed; inspect journal') from rollback
            _write(status, json.dumps({'ok': False, 'candidate': digest, 'rollback_failed': False}) + '\n')
            raise ConfigError('nginx apply failed; previous configuration restored') from exc
        if old is not None:
            _write(previous, old)
        _write(status, json.dumps({'ok': True, 'active': digest}) + '\n')
        return True
