"""Render deterministic nginx configuration from validated structured values."""

from __future__ import annotations

import ipaddress
import re
from pathlib import Path
from repowatch.config.models import Config
from repowatch.errors import ConfigError
from repowatch.parsers.base import USER_AGENT
from repowatch.routing import compute_routes, package_path

def _path(value: str) -> str:
    if not isinstance(value, str) or not re.fullmatch(r'/[A-Za-z0-9_./+-]+', value) or '..' in value.split('/'):
        raise ConfigError('nginx: invalid filesystem path')
    return value


def render(config: Config, *, cache_dir: str = '/var/cache/nginx/repowatch',
           access_log: str = '/var/log/nginx/repo-cache.access.log',
           purge_conf: str = '/etc/nginx/repowatch/purge.conf',
           dedup_conf: str = '/etc/nginx/repowatch/dedup.map',
           probe_conf: str = '/etc/nginx/repowatch/probe.conf',
           probe_js: str = '/etc/nginx/repowatch/probe.js') -> str:
    settings = config.nginx
    _path(cache_dir)
    _path(access_log)
    key_prefix, routes, kinds = compute_routes(config)
    lines = [
        '# Generated by repowatch; edit YAML parameters, not this file.',
        f'proxy_cache_path {cache_dir} levels=1:2 keys_zone=repo_cache:64m max_size={settings.cache_max_size} inactive=180d use_temp_path=off;',
        "log_format cache_status '$remote_addr - $request \"$upstream_cache_status\" -> $upstream_addr';",
    ]
    if config.syslog_listener.enabled:
        # Distinguishes repowatch's OWN traffic (index checks + prefetch/
        # warm_cache — see parsers/base.py's USER_AGENT, already sent on
        # every such request) from real client requests, so the dashboard's
        # "Recent client requests" doesn't get polluted by our own
        # background activity — see runtime.syslog.parse_syslog_line.
        # A map (not raw $http_user_agent in the log) for two reasons: (1)
        # real client user agents (e.g. "Debian APT-HTTP/1.3 (...)") contain
        # spaces, which would break the plain space-split log line format;
        # (2) it keeps a single, boring digit in the log instead of
        # attacker-influenceable free text. Both this map{} and the
        # repowatch_requests log_format live together here, only when
        # syslog_listener is enabled — the format is otherwise unused, and
        # referencing $repowatch_is_prefetch in it without the map{} that
        # actually declares the variable would be one more thing to keep in
        # sync for no reason.
        user_agent_prefix = re.escape(USER_AGENT.split('/', 1)[0])
        lines += [
            f'map $http_user_agent $repowatch_is_prefetch {{ default 0; "~*^{user_agent_prefix}/" 1; }}',
            "log_format repowatch_requests '$remote_addr $request_method $request_uri $status "
            "$upstream_cache_status $repowatch_is_prefetch';",
        ]
    if settings.enable_dedup:
        # map{} is http-context, not server-context (unlike purge's
        # location{}, see render_purge()) — it has to sit here, as a sibling
        # of proxy_cache_path/server{}, not inside the server block. The
        # actual (duplicate -> canonical) pairs live in the separate
        # dedup_conf file (render_dedup()), rewritten whenever
        # ServiceState.cache.find_duplicate_files() finds something new — this line
        # itself never changes once enable_dedup is on.
        # Keyed on $uri, NOT $request_uri: $request_uri is the ORIGINAL,
        # unmodified request URI and never changes across an internal
        # rewrite — keying on it here caused every internal redispatch to
        # re-evaluate to the same non-empty canonical URI forever, tripping
        # nginx's own "rewrite or internal redirection cycle" guard (found
        # by hand-testing against a real nginx before this shipped). $uri
        # DOES update after `rewrite`, so the second pass (now already at
        # the canonical path) maps to "" and the loop terminates in one hop.
        _path(dedup_conf)
        lines += [
            'map $uri $repowatch_canonical_uri {',
            f'    include {dedup_conf};',
            '}',
        ]
    if settings.enable_cache_probe:
        # http-context, like the dedup map{} above — js_import can't live
        # inside server{} (unlike purge/probe's own location{} blocks, see
        # render_probe_conf()). The imported module name ("cache_probe")
        # must match the export name render_probe_js() gives its handlers.
        _path(probe_js)
        lines.append(f'js_import cache_probe from {probe_js};')
    lines += [
        'server {', f'    listen {settings.listen};', f'    server_name {settings.server_name};',
        f'    resolver {" ".join(settings.resolvers)} valid=300s ipv6=off;',
        '    resolver_timeout 5s;', f'    access_log {access_log} cache_status;',
        '    proxy_cache repo_cache;', f'    proxy_cache_valid 200 206 {settings.package_ttl}s;',
        '    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;',
        '    proxy_cache_lock on;', f'    proxy_cache_key "{key_prefix}$scheme$proxy_host$request_uri";',
        '    add_header X-Cache-Status $upstream_cache_status always;',
        '    location / { return 404; }',
    ]
    if config.syslog_listener.enabled:
        try:
            address = ipaddress.ip_address(config.syslog_listener.bind)
        except ValueError as exc:
            raise ConfigError('nginx: syslog bind must be a literal IP') from exc
        if not address.is_loopback or not 1 <= config.syslog_listener.port <= 65535:
            raise ConfigError('nginx: syslog destination must be loopback with a valid port')
        host = f'[{address}]' if address.version == 6 else str(address)
        lines.append(f'    access_log syslog:server={host}:{config.syslog_listener.port},facility=local6,tag=repowatch,severity=info repowatch_requests;')
    for number, (local, (scheme, host, remote, ttl)) in enumerate(sorted(routes.items())):
        # All mutable metadata (including signatures and apt translations) get short TTL.
        patterns = (r'[^/]+\.(db|files)(\.tar\.(gz|xz|zst))?(\.sig)?$',
                    r'dists/', r'APKINDEX\.tar\.gz$', r'repodata/', r'base/', r'[^/]+-repodata$',
                    r'(nix-cache-info|[^/]+\.narinfo)$', r'Packages(\.gz)?$',
                    r'(.*\/)?(PACKAGES\.TXT|CHECKSUMS\.md5|FILELIST\.TXT|ChangeLog\.txt|MANIFEST|GPG-KEY)(\.(gz|bz2))?(\.asc)?$')
        kind = kinds[local]
        pattern = patterns[('pacman', 'apt', 'apk', 'dnf', 'apt-rpm', 'xbps', 'nix', 'gentoo', 'slackware').index(kind)]
        for index in (True, False):
            location = f'~ ^{re.escape(local)}{pattern}' if index else local
            lines += [f'    location {location} {{']
            if not index and settings.enable_dedup:
                # Dedup only ever applies to package files, never index
                # files — each repo's own index must always reflect ITS
                # OWN real state. $repowatch_canonical_uri is another
                # repo's local URI for the SAME (filename, content_hash);
                # `rewrite ... last` re-dispatches to THAT repo's own
                # location block, so whatever it does (TTL, upstream,
                # revalidate) applies unchanged. The cache key override
                # below (proxy_cache_key ...$uri, not the server-level
                # default's $request_uri) is what actually makes the
                # rewritten request land on the SAME cache entry the
                # canonical repo's own direct requests use — $request_uri is
                # the ORIGINAL, pre-rewrite URI and would keep the
                # duplicate's own path baked into the key even after
                # landing in the canonical location, silently defeating the
                # whole point (a real bug caught by hand-testing: it also
                # produced a second, separate cache entry instead of
                # sharing the canonical one).
                #
                # set $repowatch_canonical_uri ""; is NOT redundant — nginx
                # caches a map-derived variable's value for the rest of the
                # request once it's been read once, even across an internal
                # `rewrite ... last` redirect that changes $uri itself. Real
                # bug caught by hand-testing: without this reset, arriving
                # at the canonical repo's OWN location (which runs this
                # exact same check) re-read the STALE cached value from the
                # duplicate's location and rewrote again, forever — nginx's
                # "rewrite or internal redirection cycle" guard, not a
                # silent bug, but a 500 on every deduped request. The target
                # must be captured into a separate variable BEFORE the
                # reset, since `rewrite` evaluates its argument at the point
                # it runs, after this line.
                lines += [
                    '        if ($repowatch_canonical_uri) {',
                    '            set $repowatch_dedup_target $repowatch_canonical_uri;',
                    '            set $repowatch_canonical_uri "";',
                    '            rewrite ^ $repowatch_dedup_target last;',
                    '        }',
                ]
            lines.append(f'        set $rw_backend_{number} {host};')
            if local != remote:
                lines.append(f'        rewrite ^{re.escape(local)}(.*)$ {remote}$1 break;')
            lines += [f'        proxy_pass {scheme}://$rw_backend_{number};',
                      '        proxy_http_version 1.1;', f'        proxy_set_header Host {host};',
                      '        proxy_ssl_server_name on;']
            if kind == 'nix':
                basis = '$uri$is_args$args' if settings.enable_dedup else '$request_uri'
                lines.append(f'        proxy_cache_key "{key_prefix}$scheme$proxy_host{basis}";')
                lines.append('        proxy_cache_valid 404 1s;')
                if not index:
                    # Defining the negative TTL replaces the inherited TTL list.
                    lines.append(f'        proxy_cache_valid 200 206 {settings.package_ttl}s;')
            if index:
                if kind == 'pacman':
                    lines.append(f'        proxy_cache_key "{key_prefix}arch-index-v2:$scheme$proxy_host$request_uri";')
                lines.append(f'        proxy_cache_valid 200 206 {ttl}s;')
            else:
                if settings.enable_dedup and kind != 'nix':
                    # $uri (not $request_uri, see above) — applied to every
                    # content location uniformly when dedup is on, not just
                    # ones with a duplicate right now, so the key format
                    # never depends on whether a mapping currently exists.
                    # Harmless for everything else: package filenames never
                    # contain characters requiring percent-decoding or
                    # normalization here (see _uri()'s validation), so $uri
                    # and $request_uri are byte-identical for any request
                    # nginx would ever actually match against these
                    # locations — this doesn't invalidate the existing disk
                    # cache on upgrade.
                    lines.append(f'        proxy_cache_key "{key_prefix}$scheme$proxy_host$uri";')
                if kind == 'apt-rpm':
                    # ALT disttag/buildtime can change without changing the RPM
                    # basename. Revalidate these objects; the generic 180d immutable
                    # package TTL would keep an old rebuild under the same URL.
                    lines.append(f'        proxy_cache_valid 200 206 {min(ttl, settings.package_ttl)}s;')
                    lines.append('        proxy_cache_revalidate on;')
            lines.append('    }')
    if settings.enable_purge:
        # Purge/administrative locations live in their own included file
        # (render_purge()) instead of being interleaved into this per-repo
        # content-routing loop — keeps the main generated config readable as
        # the set of optional features grows, and keeps the purge file's own
        # diff/rollback independent of routing changes in apply().
        _path(purge_conf)
        lines.append(f'    include {purge_conf};')
    if settings.enable_cache_probe:
        # See render_probe_conf() — same "own included file, not interleaved
        # into per-repo routing" reasoning as purge_conf above.
        _path(probe_conf)
        lines.append(f'    include {probe_conf};')
    return '\n'.join(lines + ['}', ''])


def render_purge(config: Config) -> str:
    """Cache-eviction locations (docs_dev/ROADMAP.md item 24), generated
    separately from render() and pulled into the server block via a single
    `include` line there. Meant to be written to the path passed as
    render()'s purge_conf and included verbatim inside `server { ... }`, so
    it needs no server-level directives of its own.

    Returns just a header comment (no locations) when nginx.enable_purge is
    off, so callers can always call and write this unconditionally without
    checking the flag themselves — render() only ever includes the file when
    the flag is on, so an empty file here is inert either way.
    """
    settings = config.nginx
    key_prefix, routes, kinds = compute_routes(config)
    lines = ['# Generated by repowatch; edit YAML parameters, not this file.']
    if settings.enable_purge:
        for local, (scheme, host, remote, ttl) in sorted(routes.items()):
            # Reconstructs the SAME cache key a real package-file request
            # under `local` would produce ($scheme here is nginx's OWN
            # listening scheme — this generator never emits `listen ... ssl`,
            # so it's always literally "http" at runtime — NOT the
            # upstream's scheme; ${scheme} braced avoids nginx parsing
            # "$scheme<hostname>" as one variable name; a real bug caught by
            # hand-testing before this ever shipped).
            #
            # The URI *basis* of that key depends on nginx.enable_dedup,
            # because render() itself uses two different bases there (see
            # its own "if settings.enable_dedup: proxy_cache_key
            # ...$uri" branch, applied to every package-file location
            # uniformly once dedup is on, not just repos with an actual
            # duplicate right now): dedup off -> the server-level default,
            # $request_uri (the ORIGINAL, pre-rewrite local request path,
            # i.e. `local` here); dedup on -> $uri, which after that same
            # location's own `rewrite ^{local}(.*)$ {remote}$1 break;` holds
            # the POST-rewrite upstream-relative path, i.e. `remote` here —
            # NOT `local`. Using `local` unconditionally (as this function
            # used to) is a REAL bug found on production (2026-09-12): with
            # dedup on, purge silently missed every real cache entry —
            # confirmed by hand, curl showed `X-Cache-Status: HIT` for a
            # file, then an immediate 404 from this same purge location for
            # the identical path, for every warmed package, on every repo,
            # not just ones with an actual duplicate.
            #
            # allow/deny (not limit_except): this location ONLY ever does
            # purge, no GET/HEAD content is served from it — restricting
            # the whole location to loopback is enough, no per-method logic
            # needed. External exposure would let anyone evict any cached
            # object; the same class of risk /metrics already guards
            # against for a different resource.
            basis = remote if settings.enable_dedup else local
            query = '$is_args$args' if kinds[local] == 'nix' else ''
            lines += [
                f'    location ~ ^/purge{re.escape(local)}(.*)$ {{',
                '        allow 127.0.0.1;',
                '        deny all;',
                f'        proxy_cache_purge repo_cache "{key_prefix}${{scheme}}{host}{basis}$1{query}";',
                '    }',
            ]
        if settings.enable_cache_probe:
            # Route-independent purge (docs_dev/ROADMAP.md item 8) — accepts
            # an arbitrary already-known key verbatim, unlike the per-route
            # locations above. Needed for genuine orphans: a repo that was
            # removed from config.yaml (or had its dedup/url_template
            # settings changed) no longer has ANY route this generator can
            # rebuild a matching /purge<prefix> for, so the normal purge
            # mechanism above structurally cannot reach it. Discovery
            # (finding such a stale key at all) is cache/probe.py's
            # /cache-scan job — this location only ever deletes a key it's
            # explicitly handed, never searches for one itself. Gated on
            # BOTH flags: pointless without enable_purge (no module loaded
            # to do the actual eviction) and without enable_cache_probe
            # (nothing produces raw keys to feed it).
            lines += [
                '    location = /purge-raw {',
                '        allow 127.0.0.1;',
                '        deny all;',
                '        proxy_cache_purge repo_cache $arg_key;',
                '    }',
            ]
    return '\n'.join(lines) + '\n'


def _js_string(value: str) -> str:
    return "'" + value.replace('\\', '\\\\').replace("'", "\\'") + "'"


def render_probe_js(config: Config, *, cache_dir: str = '/var/cache/nginx/repowatch') -> str:
    """njs script body for the /cache-probe and /cache-scan locations
    (docs_dev/ROADMAP.md item 8, render_probe_conf()) — read-only cache
    introspection running inside the nginx worker itself (already `user
    www-data`-equivalent, unlike repowatch's own unprivileged process).

    Deliberately dumb: every byte of policy (which key, what counts as a
    match, what to do about an orphan) stays in Python, where it's covered
    by pytest — this only exposes two stateless filesystem primitives,
    mirroring the "njs computes nothing repowatch doesn't already know how
    to compute" principle agreed on for this feature. Both handlers were
    verified by hand against a real nginx 1.24 (Ubuntu, njs 0.8.2) cache
    directory before this was written — the cache file's on-disk header
    format is NOT public API, only empirically confirmed for that build:
    a fixed-size binary header followed by a literal "\\nKEY: <key>\\n" line
    immediately before the raw HTTP response. extractKey() searches for
    that marker instead of hardcoding the header's byte length, since the
    exact offset could differ with e.g. Vary — the marker text itself was
    what was actually confirmed stable across sample files, not one
    specific offset.

    Returns just a header comment when nginx.enable_cache_probe is off —
    render() never emits `js_import` for this file in that case, so nginx
    never parses it; the same "always safe to write unconditionally"
    contract as render_purge()/render_dedup().
    """
    settings = config.nginx
    lines = ['// Generated by repowatch; edit YAML parameters, not this file.']
    if not settings.enable_cache_probe:
        return '\n'.join(lines) + '\n'
    script = Path(__file__).with_name("probe.js").read_text(encoding="utf-8")
    script = script.replace("__REPOWATCH_CACHE_DIR__", _js_string(cache_dir))
    return "\n".join(lines) + "\n" + script


def render_probe_conf(config: Config) -> str:
    """Locations for /cache-probe and /cache-scan (see render_probe_js()),
    generated separately from render() and pulled into the server block via
    a single `include` line there — same pattern as render_purge().

    Returns just a header comment when nginx.enable_cache_probe is off,
    same "always safe to call/write unconditionally" contract as
    render_purge()/render_dedup().
    """
    settings = config.nginx
    lines = ['# Generated by repowatch; edit YAML parameters, not this file.']
    if settings.enable_cache_probe:
        lines += [
            '    location = /cache-probe {',
            '        allow 127.0.0.1;',
            '        deny all;',
            '        js_content cache_probe.probe;',
            '    }',
            '    location = /cache-scan {',
            '        allow 127.0.0.1;',
            '        deny all;',
            '        js_content cache_probe.scan;',
            '    }',
        ]
    return '\n'.join(lines) + '\n'


def _map_literal(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def resolve_dedup_pairs(config: Config, rows: list[tuple[str, str, str]]) -> list[tuple[str, str]]:
    """Turns ServiceState.cache.find_duplicate_files() rows (repo ids + filename)
    into (duplicate_local_uri, canonical_local_uri) pairs, reusing
    routing.package_path — the same function that builds warm/purge URLs —
    so a dedup entry always points at exactly the URI that repo's own
    content location actually serves.

    A repo id that no longer exists in config.repos (removed since the hash
    was recorded — repo_packages rows are orphaned on repo removal, see
    CLAUDE.md) is silently skipped, same tolerance already applied to
    warmed_packages/prefetch_bans elsewhere.
    """
    by_id = {repo.id: repo for repo in config.repos}
    pairs: list[tuple[str, str]] = []
    for duplicate_id, canonical_id, filename in rows:
        duplicate_repo = by_id.get(duplicate_id)
        canonical_repo = by_id.get(canonical_id)
        if duplicate_repo is None or canonical_repo is None:
            continue
        pairs.append((package_path(duplicate_repo, filename), package_path(canonical_repo, filename)))
    return pairs


def render_dedup(config: Config, pairs: list[tuple[str, str]]) -> str:
    """Cross-repository dedup map (docs_dev/ROADMAP.md item 29), generated
    separately from render() and pulled in via the `map { include ...; }`
    block there (see render()) — unlike render_purge()'s location{} blocks,
    a bare list of "key" "value"; lines here IS valid nginx map-file syntax
    on its own, no wrapper needed.

    `pairs` are already-resolved local URIs (see resolve_dedup_pairs) —
    this function doesn't touch ServiceState/config.repos lookups itself, to
    keep it a pure, easily-tested function of its arguments, same as
    render_purge().
    """
    lines = ['# Generated by repowatch; edit YAML parameters, not this file.']
    for duplicate_uri, canonical_uri in pairs:
        lines.append(f'{_map_literal(duplicate_uri)} {_map_literal(canonical_uri)};')
    return '\n'.join(lines) + '\n'
